### ISSUE TITLE
Collective Job hunting iterations

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#107]
### Background

@kfklein15 made notes from the London session https://docs.google.com/document/d/1EiSEH9nagUBFPSntrGvzdmgla80S4do8RrWpmB8Eaak/edit

Need to continue to iterate on the session to make it more flipped classroom & more self-lef

### Acceptance criteria

- [x] Discuss flipping the classroom with Mitch
- [x] Iterate once for WM and once for NW
- [x] Re-write notes with learnings for WM and NW session
- [ ] Write new ticket for creating plan and testing in Glasgow in May

### Owner

@barny-6

### Stakeholder

@kfklein15 

### Approver

@barny-6

**Comment by kfklein15** [comment]
https://cyf-curriculum.netlify.app/guides/employability/job-search/

**Comment by Barny-6** [comment]
Turn into guide

**Comment by Barny-6** [comment]
@kfklein15 this is ready for review. If approved we can put it into guides as 3 parts. I do wonder what the difference between guides and workshops are?

**Comment by kfklein15** [comment]
Did you send me a PR to review this?

Workshops should be exercises.
Guides are processes/check-list/guidances.
