### ISSUE TITLE
Hiring Manager 1-pager

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#109]
### Background

Create Hiring Manager 1-pager like [this example ](https://mcusercontent.com/59088989534eb306a86c96cd4/files/b93f79b4-72fe-7f00-ce47-fb4300a528ec/Partnerships_Leaflet.02.pdf) using work from https://github.com/CodeYourFuture/pd-prod-emp/issues/112#issue-2146614507

It should include our 5 value points:
- Where do our grads work
- What roles do they fill
- How do they do in those roles
- Why is parntershing with us important
- How do we make life easier for hiring managers

### Acceptance criteria

- [ ] Draft 1-pager written as Doc
- [ ] Reviewed by @gbencci and @alecmmcrindle
- [ ] Design by alec
- [ ] Added to all emails and shared with community 

### Owner

@barny-6

### Stakeholder

@alecmccrindle @gbencci

### Approver

@barny

**Comment by Barny-6** [comment]
https://docs.google.com/document/d/1GwPWf49SsWSNM9jhrtr6gecaLPhRHP8WTAkHQ_Lxz-Y/edit

**Comment by Barny-6** [comment]
https://docs.google.com/document/d/1xVbZlqi95kVmm3pMTTukDqwYT6wxZHnpvoZ171pDvCE/edit

**Comment by Barny-6** [comment]
@kfklein15 @gbencci do you have anything to add? Maybe something on CYF+?

**Comment by alecmccrindle** [comment]
Once this copy is approved @Barny-6, please add it to [CodeYourFuture Global Team PUBLIC](https://github.com/orgs/CodeYourFuture/projects/36). Thanks.

**Comment by kfklein15** [comment]
Made some suggestions. I tihnk it's good for a first version.

**Comment by Barny-6** [comment]
Dara Emma made these:[draft 1](https://www.canva.com/design/DAGFctCIWJY/a6oXmERCjf6yzWnjGMPxMw/edit)
[draft 2](https://www.canva.com/design/DAGFcu0IvGY/oA64Ws9TeqemrIuOGZXHJw/edit?utm_content=DAGFcu0IvGY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by Barny-6** [comment]
Need to update draft with feedback and Okay with all

**Comment by Barny-6** [comment]
@alecmccrindle and @kfklein15 please could you review this final draft https://www.canva.com/design/DAGFctCIWJY/a6oXmERCjf6yzWnjGMPxMw/edit

**Comment by kfklein15** [comment]
Looks pretty. How will this be used?

Feedback:
- should we swap Cyber Security for DevOps?
- I like bullet points rather than long text, because it goes straight to the point. Does it really make a difference? If yes, I would focus on that
- We make life easier for hiring managers: the paragraph after this title doesn't really show me what difference you will make and how/why you are making my life easier. Can we add some stats/numbers of actual value?

**Comment by Barny-6** [comment]
https://drive.google.com/file/d/1G_bSuKHSsLG5dXLV2-SNhZvs1UGgWsgy/view?usp=sharing
