### ISSUE TITLE
Oak applications post mortem

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#115]
### Background

29/30 applicants were rejected. They have been given their scores and feedback. We need to collectively do a retro to understand what can be learned for their next applications.

### Acceptance criteria

- [ ] Find 2/3 grads to lead
- [ ] Collect successful and unsuccessful answers in shared location
- [ ] Gather thoughts and feedback
- [ ] Host retro to discuss and set actions

### Owner

@barny-6

### Stakeholder

@kfklein15 @gbencci

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://docs.google.com/document/d/1vHjggKlc3Pr2rkYihER-e9yjWynJgAmMcHZRRvJ2sgc/edit

**Comment by Barny-6** [comment]
@kfklein15 I've started collecting in feedback and done a post that outlines our bigger gaps. I'm hoping the volunteers who were involved and the grads start working together on the feedback but I also think it's worth raising with the wider community that there are some clear weaknesses that we can work on collectively. Are you okay to keep an eye on their progress next week?

**Comment by kfklein15** [comment]
Retro conversation on [Slack](https://codeyourfuture.slack.com/archives/C02G8KW7469/p1718727112079749)
