### ISSUE TITLE
Identify and contact volunteers to contact employers

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#118]
### Background

Use [this spreadsheet]([Volunteers Employers](https://docs.google.com/spreadsheets/d/1vjRQppmzyE4EVmOX_CMXv2xnraALuD7a2ZLSEMqJaD4/edit?usp=sharing_eil_se_dm&ts=6661ca94)) to identify who to prioritise and then approach them using the existing templates etc 

### Acceptance criteria

- [ ] All volunteers' employers are prioritised
- [ ] Set out a timetable for contacting all volunteers

### Owner

@barny-6

### Stakeholder

NA

### Approver

@barny-6

**Comment by kfklein15** [comment]
Added all to LinkedIn and contacted.
