### ISSUE TITLE
Create Cover Letter Guide

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#120]
### Background

We are updating the new [Guides page](https://curriculum.codeyourfuture.io/guides/employability/) and want to ensure that all stages of the job application process are covered in a guide.

https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/cv-1

### Acceptance criteria

- [ ]  Guide drafted in word doc
- [ ]  Reviewed and approved by at least 1 volunteer and 1 grad
- [ ]  Reviewed against guide contribution criteria
- [ ]  Deployed as guide
- [ ]  Shared with community

### Owner

@barny-6

### Stakeholder

@kfklein15

### Approver

@barny-6

**Comment by Barny-6** [comment]
When you return please review this @kfklein15 https://cyf-guides.netlify.app/admin/#/collections/employability/entries/cover-letters/index?backTo=/dashboard

**Comment by Barny-6** [comment]
It seems the update hasn't worked for CV, I've alerted Sally but please don't publish this until we have confirmation. THanks

**Comment by kfklein15** [comment]
@Barny-6 , what does this phrase mean?
"It should be signed with a professional closing." You don't mean actually sign the letter, do you? As a foreigner, reading this I would print it and sign it :D

**Comment by Barny-6** [comment]
Updated, please review and publish @kfklein15

**Comment by kfklein15** [comment]
I am still seeing the same phrase, @Barny-6 
<img width="667" alt="image" src="https://github.com/user-attachments/assets/6e76b34c-dd54-46ff-a6f4-d0382d935e0f">
Can you send me the phrase so I can try to amend it directly?

**Comment by Barny-6** [comment]
It should be ended professionally, for example:
Thank you for you consideration.
Yours kindly,
(Your name)

**Comment by kfklein15** [comment]
Published. Please check it tomorrow.
