### ISSUE TITLE
Create GitHub guide

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#121]
### Background

We are updating the new [Guides page](https://curriculum.codeyourfuture.io/guides/employability/) and want to ensure that all stages of the job application process are covered in a guide.

https://module-graduates.codeyourfuture.io/further-activities/cv-and-job-prep/github

### Acceptance criteria

- [x]  Guide drafted in word doc
- [ ]  Reviewed and approved by at least 1 volunteer and 1 grad
- [x]  Reviewed against guide contribution criteria
- [ ]  Deployed as guide
- [ ]  Shared with community

### Owner

@barny-6

### Stakeholder

@kfklein15

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://cyf-guides.netlify.app/admin/#/collections/employability/entries/github/_index Ready for review

**Comment by Barny-6** [comment]
@kfklein15 please review when you're back :)

**Comment by kfklein15** [comment]
Published this. Let me know if it worked tomorrow.

**Comment by kfklein15** [comment]
Published ok.
