### ISSUE TITLE
Create Job Searching guide

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#124]
### Background

We are updating the new [Guides page](https://curriculum.codeyourfuture.io/guides/employability/) and want to ensure that all stages of the job application process are covered in a guide.

This guide should cover:
- Searching for a job (using job platforms, search terms, best practice etc.)
- Assessing the suitability of the job

### Acceptance criteria

- [x]  Guide drafted in word doc
- [x]  Reviewed and approved by at least 1 volunteer and 1 grad
- [x]  Reviewed against guide contribution criteria
- [ ]  Deployed as guide
- [ ]  Shared with community

### Owner

@barny-6

### Stakeholder

@kfklein15

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://docs.google.com/document/d/1t-d8upRykT33lN4RBSbiS3ngpGPHd-E_iVCgE4LTAeM/edit

**Comment by Barny-6** [comment]
@kfklein15 please review this guide and let me know your thoughts, thanks

**Comment by Barny-6** [comment]
@Barny-6 to read and implement feedback

**Comment by kfklein15** [comment]
It looks good. Comments added. I wonder if this should be a workshop considering the new SDC? Love the exercises.

**Comment by Barny-6** [comment]
I'm not sure how the SDC works to be honest but I also think the exercises are effective when people actually do them :)

**Comment by Barny-6** [comment]
@kfklein15 I've updated this into guides, please could you give it a review and we'll publish - https://cyf-guides.netlify.app/admin/#/dashboard

**Comment by kfklein15** [comment]
Published.
