### ISSUE TITLE
WTW outreach

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#129]
### Background

WTW have a few openings. Find and connect with mutual connections through Linkedin

### Acceptance criteria

- [x] Potential contact found
- [x] Reach out
- [x] Follow up
- [ ] Next steps or back out

### Owner

@barny-6

### Stakeholder

@gbencci

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://www.linkedin.com/in/lesley-bamber-a6051549?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_sent_invitations%3B2nCiQqzGSAK45bul24u%2FHQ%3D%3D

**Comment by kfklein15** [comment]
Please add what role we are looking for on this and other tickets.

**Comment by Barny-6** [comment]
[QA Engineer](https://www.linkedin.com/jobs/search/?currentJobId=3956161737&f_C=3994&geoId=101165590&location=United%20Kingdom&origin=JOB_SEARCH_PAGE_SEARCH_BUTTON&refresh=true)
- https://www.linkedin.com/in/stephen-jefferies-qa/ 

[DevOps EngineerDevOps Engineer with verification](https://www.linkedin.com/jobs/view/3956357154/?eBP=NON_CHARGEABLE_CHANNEL&refId=2Kn%2B2qdLTaEKxwgfUz0EJw%3D%3D&trackingId=UbcoxJ1xT7PcPrudb6gMqA%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BYZmA7kmfSG6IFrh49m4%2FcA%3D%3D&lici=UbcoxJ1xT7PcPrudb6gMqA%3D%3D)
- [Steven Sherwin](https://www.linkedin.com/in/steven-m-sherwin/overlay/about-this-profile/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BZ%2Bf2RDE%2FSeyiFQveSz9jQg%3D%3D)
- [Stuart Leaver](https://www.linkedin.com/in/stuartleaveruk/overlay/about-this-profile/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BCl6e7MxCSJ2D7%2BVXagWEzA%3D%3D)

[Site Reliability EngineerSite Reliability Engineer with verification](https://www.linkedin.com/jobs/view/3959510180/?eBP=NON_CHARGEABLE_CHANNEL&refId=R1lPZbeMd4PhOcfHckY%2BMg%3D%3D&trackingId=Q%2B4csoT1uDii6nEQIkLkeA%3D%3D&trk=flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BYZmA7kmfSG6IFrh49m4%2FcA%3D%3D&lici=Q%2B4csoT1uDii6nEQIkLkeA%3D%3D)

**Comment by Barny-6** [comment]
Follow up sent. No contact yet

**Comment by Barny-6** [comment]
Try Apollo

**Comment by Barny-6** [comment]
https://www.linkedin.com/in/clare-louise-lewis-she-her-b6592147/ contacted via email through Apollo

**Comment by kfklein15** [comment]
Try with one more person and then close this.
