### ISSUE TITLE
EDF Outreach

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#130]
### Background

EDF have a few openings. Find and connect with mutual connections through Linkedin

### Acceptance criteria

- [x]  Potential contacts found
- [x]  Reach out
- [ ]  Follow up
- [ ]  Next steps or back out

### Owner

@barny-6

### Stakeholder

@gbencci

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://www.linkedin.com/in/philip-fryar-7329a085/

https://www.linkedin.com/in/kate-bryan-872960142/

**Comment by kfklein15** [comment]
Clementine Whitcomb who was super active in Lon 8 and 9 I think works there.

**Comment by Barny-6** [comment]
We've tried to work something through her before. Will revisit if we don't make headway with Kate
