### ISSUE TITLE
CGI Outreach

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#131]
### Background

CGI have a few openings. Find and connect with mutual connections through Linkedin

### Acceptance criteria

- [x]  Potential contact found
- [x]  Reach out
- [ ]  Follow up
- [ ]  Next steps or back out

### Owner

@barny-6

### Stakeholder

@gbencci

### Approver

@barny-6

**Comment by Barny-6** [comment]
[Stuart Stenhouse](https://www.linkedin.com/in/clientengagement?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_sent_invitations%3BuhRZ7c2AQp6lZC8xKY9IdQ%3D%3D)

[Chris Wilcock](https://www.linkedin.com/in/chriswilcock?lipi=urn%3Ali%3Apage%3Ad_flagship3_people_sent_invitations%3BuhRZ7c2AQp6lZC8xKY9IdQ%3D%3D)

**Comment by Barny-6** [comment]
Check with @gbencci about using apollo

**Comment by Barny-6** [comment]
German to send ADam & Christopher's details to Barny 
- Check he's still at CGI
- Retry shaun

**Comment by Barny-6** [comment]
G has emailed a thread of contact

**Comment by kfklein15** [comment]
CGI introduction done via Saso (KFK's contact)
Luke Kittow, CGI UK Social Sustainability Lead. 
Lloyd Francis,  Vice President Consulting Services
