### ISSUE TITLE
Create more opportunities for technical interview practice

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#152]
### Background

Grads have requested more help on technical interview practice. Collaborate with tech-ed and Capgemini to provide more opportunities

### Acceptance criteria

- [x] Link Capgemini technical interview volunteers with tech ed
- [ ] Create guide in interview channel canvas on hosting technical interviews
- [ ] Encourage at least 5 volunteers to offer technical interviews on the channel

### Owner

@barny-6

### Stakeholder

NA

### Approver

@barny-6

**Comment by kfklein15** [comment]
Ziggy, Adrian and Adam are working on the technical interview guidance, with repo with practice tests. 
Ask Ziggy and Adam to be onboarded, so this can be publically shared on the interview channel.
