### ISSUE TITLE
Trayport Advertising

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#154]
### Background

Trayport are offering mock interviews to candidates for specific roles which G has posted about here - https://codeyourfuture.slack.com/archives/C0467D9TV70/p1721751223622899

Thursday 1st Aug we need to have a list of jobs & candidates  - Mock interviews 13th Aug 

### Acceptance criteria

- [ ] Grads share which roles they're interested in by Thursday 1st Aug
- [ ] At least 15 responses

### Owner

@barny-6

### Stakeholder

@gbencci

### Approver

@barny-6

**Comment by kfklein15** [comment]
Roles that could be available:
- Trainee Support Analyst
- SRE (no longer online)
- System Engineer
- C Sharp Data Developer
- Product Manager: could be Elena? 
- 
@Barny-6  to send the list of names and roles per person to German.
