### ISSUE TITLE
Secure guest speaker in WM

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#26]
**Background**
We have a possible guest speaker to talk about 'How to make sure that IT services / developer offers match business requirements in a company'. 

Dates available: 
- Saturday 10/02
- Less ideally 20/01,

**Acceptance Criteria**
- [ ] WM graduates asked if they want speaker (Yes/No)
- [ ] Identify dates for speaker to visit
- [ ] Confirm Yes/NO with speaker

**Owner**
@Barny-6 

**Stakeholders**
@MattCFry 

**Approver**
@Barny-6

**Comment by Barny-6** [comment]
Asked in Slack only 1 response. With cloud module I'm expecting the answer is NO.

**Comment by Barny-6** [comment]
@MattCFry Can we Yes/No this speaker? I'm thinking it's a no?

**Comment by MattCFry** [comment]
We are currently not meeting the criteria for the portfolio module so I currently can't be sure we will have a session on the exact date.

I would No this time.

Maybe another time?

**Comment by MattCFry** [comment]
I've made [this post](https://codeyourfuture.slack.com/archives/C0515NZ6TQW/p1706115513091619) to maybe jumpstart things?

Between the PF module and cloud, its hard to focus those who we can reach :(

**Comment by Barny-6** [comment]
no longer a main goal
