### ISSUE TITLE
Review platforms

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#27]
**Background**
There are a number of platforms suggested for improving employability / PD activities. This ticket is a backlog for those review requests. 

[London Team Evolution Interview Improvement App](https://codeyourfuture.slack.com/archives/C05N2R8CXUK/p1702558197397959)
[Pramp coding test support](https://codeyourfuture.slack.com/archives/C05N2R8CXUK/p1702547389608189)

**Acceptance Criteria**
- [ ] Create a separate ticket for each review that includes
- [ ] Briefly review platform to decide if a further review is worthwhile based on potential value to trainees & time save for community
- [ ] If yes, request at least 3 reviewers from community (1 volunteer & 1 grad minimum) 
- [ ] Agree review criteria with reviewers 
- [ ] Decided Yes/No on expanding review or trialling with a cohort

**Owner**
@Barny-6 

**Approver**
@Barny-6

**Comment by kfklein15** [comment]
Closing this since the world (CYF) has changed
