### ISSUE TITLE
Define criteria for guide to displaying non-project work in portfolios

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#33]
Ask the community to develop a guide of alternative ways to showcase your work. e.g. PMing, Dev-Ops etc.
https://codeyourfuture.slack.com/archives/G0143AEFSBF/p1698226029159799

**Background**
Some projects can't be demoed, such as Dev-Ops or Code Your Future Products, where a grad may not have an artifact they can display on their portfolio. As this work is still valuable experience and contributes to a grad's chances of getting a job, we need to find alternative ways of highlighting achievements and competencies. 

Case Study 1: Dev-Ops
Alongside the Cloud module, a number of grads volunteered to support CYF with Dev-Ops. This work doesn't create a project that can be displayed on a portfolio, but it is valuable work that should be highlighted. 

Case Study 2: CYF Products
Volunteering with CYF Products is a valuable route for grads to get experience working with real products that have 100s or 1000s of users. However, as these are live & complex products, they cannot be displayed as products in the same way a team project might be. 

**Acceptance Criteria**
These are the criteria for developing a document to show how to display/demonstrate non-project work in the portfolio.

In order for this guide criteria to be successful, it must:
- Be clear and concise: The language of the criteria should be easy to understand (following the standard Code Your Future curriculum language guide)
- Be easy for a graduate & volunteers to assess non-project demos against the criteria (i.e. not technically complex)
- Ensure that grads have an artefact they can add to their Portfolio pages
- The artefact highlights the work and skills of the graduates and the value of the work done

**Responsible**
@Barny-6 

**Stakeholders**
@kfklein15 @Barny-6 + 1/2 volunteers (to be confirmed)

**Approvers**
@kfklein15

**Comment by Barny-6** [comment]
Add guide for Products grads

**Comment by Barny-6** [comment]
@kfklein15 please review the criteria for this project and approve if you're happy with it. Thanks

**Comment by kfklein15** [comment]
Hi @Barny-6 ,

Looking good!

I would say your stakeholders on this ticket should also be 1-2 volunteers that do hiring? Just so we can get an input if they are also happy with these criteria?

Questions about the criteria itself. I am understanding this is the criteria for developing a document/video/whatever to show how to create this non-project work in the portfolio.
- Be clear and concise > should we add an English-level language or something that gives a reference of what clear and concise means?
- Be easy to self-assess against > easy to access against what? Not sure this is clear to me.
- Be easily reviewed by grads and volunteers > The document to be easily reviewed? Or the non-project work?
- Ensure that grads have an artefact they can add to their Portfolio pages
- The artefact highlights the work and skills of the graduates > should it also highlight the value/benefit of it?
