### ISSUE TITLE
Have launch call for the new portfolio one-pager team.

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#52]
*context*
Ali, Sam and maybe Anderson have offered to write a one-pager on what a portfolio should like. We need to agree and set a date for an initial call.

*Acceptance Criteria*
- [ ] Date set with all volunteers invited
- [ ] At least Ali & Sam join

Approver
@Barny-6

**Comment by kfklein15** [comment]
Probably a bit too short :D But I understand why
My suggestion is leaving this on the "not started" status, since you need more information to re-write it, refine it and then prioritse it.

**Comment by kfklein15** [comment]
Reduce scope to focus only on Employability. So all other tickets need to be reviewed. Thanks.

**Comment by kfklein15** [comment]
Should this be done and have another ticket just for employability?

**Comment by kfklein15** [comment]
Ask volunteers that have recently reviewed Portfolio to put a 1-page checklist together.

**Comment by Barny-6** [comment]
Team is Ali, Sam Pennington and maybe Anderson F
