### ISSUE TITLE
NW/WM engagement investigation

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#78]
### Background

See ticket [#109](https://github.com/CodeYourFuture/pd-prod-emp/issues/109)

We want to approach the grad communities and bring them together to address the low engagement and consistency within each region. Using this doc https://docs.google.com/document/d/17T1QkBToahKUP_SpuQMYqA9_KchWj_Acby9RyiyHLy8/edit

### Acceptance criteria

- [ ] Date and start criteria are agreed for call
- [ ] Call is advertised with info and sign ups obtained
- [ ] Sign ups are invited to call
- [ ] Call is held
- [ ] New tickets created from call actions

### Owner

@barny-6

### Stakeholder

@kfklein15 @gbencci @emcglackenr1

### Approver

@barny-6

**Comment by Barny-6** [comment]
Plan agreed. Next steps are to plan comms and set dates and targets. Will create new tickets for next spring

**Comment by Barny-6** [comment]
Tickets drafted here: https://docs.google.com/document/d/1Cv2AwylN32snuB9-dz8t-G4EuLpihSU9QTxEEsIdFIk/edit?usp=sharing

**Comment by Barny-6** [comment]
Hello @kfklein15 @gbencci @lilianabermudes I've created a series of new tickets here which I intend to run next sprint . Please could review and give feedback if you have any:  https://docs.google.com/document/d/1Cv2AwylN32snuB9-dz8t-G4EuLpihSU9QTxEEsIdFIk/edit?usp=sharing

**Comment by kfklein15** [comment]
I have left my comments on it.

**Comment by Barny-6** [comment]
@lilianabermudes , @gbennci having discussed with @kfklein15 I'm going to close this ticket for now and focus expressly on connecting with the community for hiring opportunities. If things come up that can promote engagement I will pass them on but otherwise, I'll focus on bringing them together for job hunting only
